import { useState } from 'react'
import { Link } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { useApp } from '../context/AppContext'
import { activities, categoryInfo } from '../data/catalog'

const formatDate = (date: string) => new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric', year: 'numeric' }).format(new Date(date))

export function CreationsPage() {
  const { data, deleteCreation, deleteIdea } = useApp()
  const [filter, setFilter] = useState<'all' | 'in-progress' | 'completed'>('all')
  const creations = data.creations.filter((item) => filter === 'all' || item.status === filter)
  const remove = (id: string, title: string) => { if (window.confirm(`Delete “${title}”? This cannot be undone.`)) deleteCreation(id) }
  return <div className="section-wrap page"><PageHeader eyebrow="Your private collection" title="My Creations">Return to an idea, finish a project, or simply see what you have explored. Only you can see work saved here.</PageHeader><div className="tab-list" role="group" aria-label="Filter creations">{(['all', 'in-progress', 'completed'] as const).map((item) => <button className={filter === item ? 'active' : ''} aria-pressed={filter === item} onClick={() => setFilter(item)} key={item}>{item === 'all' ? 'All' : item === 'in-progress' ? 'In progress' : 'Completed'}</button>)}</div>{creations.length > 0 ? <div className="creation-list">{creations.map((creation) => { const activity = activities.find((item) => item.id === creation.activityId); if (!activity) return null; return <article className="creation-card" key={creation.id}><div className={`card-icon accent-${categoryInfo[activity.category].color}`} aria-hidden="true">{categoryInfo[activity.category].icon}</div><div className="creation-body"><div className="creation-heading"><div><p className="eyebrow">{activity.title} · {activity.category}</p><h2>{creation.title}</h2></div><span className={`status status-${creation.status}`}>{creation.status === 'completed' ? '✓ Completed' : '● In progress'}</span></div><p className="date-line">Created {formatDate(creation.createdAt)} · Updated {formatDate(creation.updatedAt)}</p><div className="creation-actions"><Link className="button button-small" to={`/create/${activity.id}?creation=${creation.id}`}>{creation.status === 'completed' ? 'View or edit' : 'Continue creating'}</Link><button className="text-button danger" onClick={() => remove(creation.id, creation.title)}>Delete</button></div></div></article> })}</div> : <div className="empty-state"><span aria-hidden="true">✏️</span><h2>{data.creations.length ? 'Nothing in this view' : 'Your first idea starts here'}</h2><p>{data.creations.length ? 'Choose another filter to see your work.' : 'Pick an activity, add your own ideas, and save whenever you are ready.'}</p><Link className="button" to="/activities">Explore Activities</Link></div>}{data.savedIdeas.length > 0 && <section className="saved-ideas"><div className="section-heading"><div><p className="eyebrow">Sparks for later</p><h2>Saved ideas</h2></div></div><div className="mini-grid">{data.savedIdeas.map((idea) => <article className="mini-card" key={idea.id}><span aria-hidden="true">✦</span><div><p className="eyebrow">{idea.difficulty}</p><h3>{idea.prompt}</h3><button className="text-button danger" onClick={() => deleteIdea(idea.id)}>Remove</button></div></article>)}</div></section>}</div>
}
