import { Link, useLocation } from 'react-router-dom'
import { PageHeader } from '../components/PageHeader'
import { useApp } from '../context/AppContext'
import { achievements, activities, categoryInfo } from '../data/catalog'
import type { Category } from '../types/models'
import { calculateStreak } from '../utils/progress'

const skillMap: Record<Category, string> = { 'Art & Design': 'Creativity', 'Idea Lab': 'Innovation', 'Brain Challenges': 'Problem Solving', 'Story Studio': 'Communication', 'Code Lab': 'Technology', 'Discovery Lab': 'Curiosity' }

export function ProgressPage() {
  const { data } = useApp()
  const location = useLocation()
  const completed = data.creations.filter((item) => item.status === 'completed')
  const explored = new Set(completed.map((creation) => activities.find((activity) => activity.id === creation.activityId)?.category).filter(Boolean) as Category[])
  const streak = calculateStreak(data.participationDates)
  const newCompletion = (location.state as { completed?: string } | null)?.completed
  return <div className="section-wrap page"><PageHeader eyebrow="Your creative journey" title="Look what you’ve explored">Progress is a quiet record of trying, making and learning. There are no rankings and no pressure to keep a streak.</PageHeader>{newCompletion && <div className="celebration" role="status"><span aria-hidden="true">✦</span><div><strong>Creation completed!</strong><p>You finished “{newCompletion}”. Your progress has been updated.</p></div></div>}<section className="stats-grid" aria-label="Progress summary"><article><span aria-hidden="true">✓</span><strong>{completed.length}</strong><p>Activities completed</p></article><article><span aria-hidden="true">⌁</span><strong>{explored.size} / 6</strong><p>Categories explored</p></article><article><span aria-hidden="true">☀</span><strong>{streak}</strong><p>Creative days in a row</p><small>Missing a day is always okay.</small></article></section><section className="progress-section"><div className="section-heading"><div><p className="eyebrow">Skills grow through practice</p><h2>Skills explored</h2></div></div><div className="skills-grid">{Object.entries(categoryInfo).map(([category, info]) => { const count = completed.filter((creation) => activities.find((activity) => activity.id === creation.activityId)?.category === category).length; return <article className={count ? 'skill-card active' : 'skill-card'} key={category}><span aria-hidden="true">{info.icon}</span><h3>{skillMap[category as Category]}</h3><p>{count ? `${count} completed ${count === 1 ? 'activity' : 'activities'}` : 'Ready to explore'}</p><div className="skill-meter"><span style={{ width: `${Math.min(100, count * 25)}%` }} /></div></article> })}</div></section><section className="progress-section"><div className="section-heading"><div><p className="eyebrow">Moments worth noticing</p><h2>Achievements</h2></div><span>{data.achievements.length} of {achievements.length}</span></div><div className="achievement-grid">{achievements.map((achievement) => { const unlocked = data.achievements.find((item) => item.id === achievement.id); return <article className={unlocked ? 'achievement-card unlocked' : 'achievement-card'} key={achievement.id}><span aria-hidden="true">{unlocked ? achievement.icon : '◇'}</span><div><h3>{achievement.title}</h3><p>{achievement.description}</p>{unlocked && <small>Explored {new Intl.DateTimeFormat(undefined, { month: 'short', day: 'numeric' }).format(new Date(unlocked.unlockedAt))}</small>}</div></article> })}</div></section>{completed.length === 0 && <div className="start-nudge"><h2>Your journey is ready</h2><p>Completing one activity will reveal your first achievement and skill.</p><Link className="button" to="/activities">Find an activity</Link></div>}</div>
}
